# Generated by Django 2.0.7 on 2018-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=265)),
                ('last_name', models.CharField(max_length=265)),
                ('email', models.CharField(max_length=265)),
                ('age', models.IntegerField(blank=True)),
            ],
        ),
    ]
